# Setup
title:               David's blog
tagline:             'Who knows.'
description:         'My blog.'
url:                 https://dprelogo.github.io
baseurl:             '/blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              David Prelogović
  url:               https://github.com/dprelogo
  email:             david.prelogovic@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
excerpt_separator: <!--more-->

# collections:
#   tags:
#     output: true
#     permalink: tags/:path/