# Setup
title:               David's blog
tagline:             'yet another'
description:         "The blog's purpose: life is short. The more you write, the more you think there has to be something better to do with your life."
url:                 https://dprelogo.github.io
baseurl:             '/blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              David Prelogović
  url:               https://github.com/dprelogo
  email:             david.prelogovic@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
excerpt_separator: <!--more-->

# collections:
#   tags:
#     output: true
#     permalink: tags/:path/

collections:
  tag:
    output: true
  cat:
    output: true

# Giscus Comments Configuration
giscus:
  repo: "dprelogo/blog"
  repo_id: "R_kgDOJZqSNw"
  category: "Announcements"
  category_id: "DIC_kwDOJZqSN84CurQm"
  mapping: "pathname"
  strict: "0"
  reactions_enabled: "1"
  emit_metadata: "1"
  input_position: "top"
  theme: "light"
  lang: "en"

