# Setup
title:               David's blog
tagline:             'Is blogging still a thing?'
description:         'The purpose of this blog is to appreciate the fact that life is short. The more I write, the more I think there has to be something better to do with my life right now.'
url:                 https://dprelogo.github.io
baseurl:             '/blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              David Prelogović
  url:               https://github.com/dprelogo
  email:             david.prelogovic@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
excerpt_separator: <!--more-->

# collections:
#   tags:
#     output: true
#     permalink: tags/:path/

collections:
  tag:
    output: true
  cat:
    output: true

